name: Deploy with HCP Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.ARM_CREDENTIALS }}

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform Changes
      run: terraform plan -out=tfplan

    - name: Apply Terraform Changes
      if: success()
      run: terraform apply tfplan
